### ISSUE TITLE
massFlux and parentSI seem incompatible

### ISSUE THREAD

**Issue by maier-m** [NCEAS/eml#284]
`massFlux` has a parentSI of `kilogramsPerSecond`
A more appropriate `massFlux` SI would be `kilogramsPerSquareMeterPerSecond`
`kilogramsPerSecond` would be more appropriately `massRate`

**Comment by mobb** [comment]
agreed (flux has area in the denominator). 
also applies to amountOfSubstanceWeightFlux, which might be a mass-specific rate (?)

other instances of the term "flux" to note: 
1. massflux unitType is named arealMassDensityRate, which is fine as is.

2. magneticFlux and magneticFluxDensity include area - sometimes in the numerator, sometimes denominator. Perhaps this is because of unit reductions? Knowing nothing about magnetism, I am not qualified to edit  these.

**Comment by mobb** [comment]
Also note, this one is actually is a mass "flux", but is called a rate. 

simplest solution is to rename the unitTypes, and confirm the children match: 

massFlux 
` <unitType id="arealMassDensityRate" name="arealMassDensityRate">
    
    <dimension name="mass"/>
    <dimension name="length" power="-2"/>
    <dimension name="time" power="-1"/>
  </unitType>`

amountOfSubstanceWeightRate
` <unitType id="amountOfSubstanceWeightFlux" name="amountOfSubstanceWeightFlux">
    
    <dimension name="amount"/>
    <dimension name="mass" power="-1"/>
    <dimension name="time" power="-1"/>
  </unitType>`

massRate:
`<unitType id="massFlux" name="massFlux">
    
    <dimension name="mass"/>
    <dimension name="time" power="-1"/>
  </unitType`

**Comment by mobb** [comment]
related to #285

**Comment by mobb** [comment]
1. massFlux is now massRate
2. arealMassDensityRate is now massFlux
3. amountOfSubstanceWeightFlux is now amountOfSubstanceWeightRate
