### ISSUE TITLE
milliGramsPerMilliLiter inconsistent format

### ISSUE THREAD

**Issue by maier-m** [NCEAS/eml#286]
`milliGramsPerMilliLiter` should be `milligramsPerMilliliter` for consistent formatting

**Comment by mobb** [comment]
I agree in principle that these are inconsistent, but to change the built-in unit list in v 2.2 would be a backwards-incompatible change, and to simply add new units with alternate spellings is likely to be confusing.  Since this list does not really conform to a standard, the element name (standardUnit) is a bit of a misnomer. It's better to think of them as 'predefined', or 'built-in'.

There are community efforts to design libraries of units. the one I work with was put together by the LTER network (unit.lternet.edu), and will be migrated to EDI. This dictionary delivers unit descriptions via web services, so makes it relatively to use customUnit instead of relying on the predefined list.

**Comment by mobb** [comment]
done, deprecated.
