### ISSUE TITLE
Describe blank cells with missing value codes

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/eml#299]
Currently, there is no good way to describe the meaning of empty cells in a data table. Although explicitly specifying the missing value codes in a dataset (and not leaving cells blank) is clearly preferred, it is not uncommon to find blank cells in datasets. To preserve provenance between original datasets and derived datasets, these blank cells must be retained, and described in the metadata.

Since you cannot have an empty string in the `code` tag, we usually have to resort to inserting some placeholder text such as "blank" into the tag. This isn't exactly correct though, since the cell with the missing value obviously doesn't have the word "blank" in it. 

@csjx suggested giving the `code` element a `blank` attribute, which, when set to true, indicates that any content in the `code` element should be ignored.

I do think we should consider finding a solution to this. The datateam frequently runs into this problem and our solutions at the moment are kludgey and inconsistent.

**Comment by mobb** [comment]
Blank fields might make a table easy on the eyes in a spreadsheet, but they present lots of problems. If your file with blank fields has a character delimiter, be sure to set collapse delimiter to "no". Sometimes even with that metadata, whitespace delimiters are collapsed, and the result is jagged rows. 

Since handling of missingValueCode is to match a string, how do you to match nothing?  The only way (I think...) would be to relax the requirement that missingValueCode be a nonEmptyString type, so that you could say <missingValueCode/>. Any other content (NULL, \s+, ' ', blank) is incorrect, or would require a special practice.  IMO, blank fields should be avoided.

Tagging this issue as 'documentation'.

**Comment by mobb** [comment]
Yes, when documenting someone else's data, and you can't make changes, this is a huge problem. And you probably have to choose an action that fits within your group's protocols for curation (based on whether you have contact with the scientist, etc).  

If you have no contact with the originator, and no idea what a blank means (not collected, not analyzed, broken instrument, my dog ate sample, ...), probably the safest course of action is to not put a missingValueCode in at all, and in the attributeDescription, say outright that "this column contains blank fields". But of course, you should confirm that with the folks creating your curation protocols.

**Comment by mobb** [comment]
Text of a similar conversation on slack, that explains why empty fields are not a good idea:
 
12:25 PM
 quick EML question about missing values:  If I want to specify that an empty cell in a .csv means "data not collected", how do I encode the "empty cell" in EML?  I found this online:  `<code>null</code>` but I don't think 'null' is the same as 'empty'.  Thanks for any insights you may have!

12:26 PM
personally, I don;t think an empty cell is a good idea - too often whitespace gets eaten up by processor.
in a DB, an empty string is not the same thing as a null

12:28 PM
I've never used an empty cell before, but this is a special case.

12:28 PM
so in the a csv, do you have rows something like this?
value1,value2,,value4...

12:28 PM
yes

12:49 PM
by having nothing in there at all (ie, you have ,, in the data file - lets call it commacomma), then you are leaving it up to the user to figure out how to deal with the empty field. (is it a null? space? NaN, 0? the program or person using it will have to decide on its own.)

The point of having metadata is to tell users how to interpret - so missingValueCode tells a row-parser how to treat this value during import.

So if the line of data has commacomma, technically there is nothing you _can_ tell a parser (nothing to define in a code-description pair). So no missingValueCode at all is technically correct.

But for humans, it would be nice to tell them whatever you can. you could create a hack - eg, you could put
```<code>empty field</code>
<description>field deliberately left empty</description>
```
and assume they would read it.  The risk is that somewhere else in that column, there might be a legitimate value that is the same string ("empty field"), and that value would actually get filtered, out too!.

I don't actually remember what pasta does with a commacomma  or what we said in BP either! (edited) 
if you do leave it commacomma, be sure to say
`collapseDelimiters="no"`
if a row parser were to assume you could collapse delimiters, then the commacomma would get turned into just one comma and you'd have a row that was too short. (edited) 

12:58 PM
I see.  Perhaps I can talk the PI into accepting a NaN instead of an empty field.  Thank you for this thorough explanation of the problem with the commacomma!

12:59 PM
asking for a NaN is a good idea!
if they say 'no', and you do know why the empty field is there, your human-hack could certainly be more friendly, than 'deliberately left empty'.

**Comment by amoeba** [comment]
How workable is it to make it standard, in this case, to _not_ specify a missing value code at all to indicate no coding scheme is being used by the researchers to indicate missingness, they just either have data (`,foo,`), or no data (`,,`). This makes the distinction that missing value codes are positive assertions of a coding scheme used by the researchers and a file just having no data in a slot (a NULL value in a NetCDF or a `,,` in CSV is not the same thing.

To drive with an example, say I went to _integrate_ two datasets, one that uses `-9999` as a missing value code and the other just has blank cells and no missing value codes. If I load both into R (say, from a CSV in both cases), and filter the values in each dataset by their missing value codes (which is only `-9999` for the first file, none for the second) in order to remove missing values, things work fine because R, by default, interprets `,,` in a CSV as an `NA`. This is a bit of a weak example because it relies on non-standardized behavior in CSVs parsers to prove my point but it works.

If we are throwing a value like `blank` in the missing value codes, my example still works fine because no non-missing values get filtered so long as `blank` isn't a real data value in the dataset.

**Comment by mobb** [comment]
I think I see your point - that a MVC is also an assertion that all values not matching `<code>` are not missing values. So it might be misleading to put something in there that is not intended for string-matching. There is still an option to communicate with human users thru `attributeDescription` (and `addtionalInfo` at the entity level), so that is better practice that hacking MVC for human readable text.

**Comment by amoeba** [comment]
Thanks @mobb 	

@jeanetteclark, @csjx: Is my idea totally off base?

**Comment by mbjones** [comment]
Interesting thread.  I think that the `commacomma` that you so named is implicitly a `NULL` value in database speak, which we generally equate to an `NA` in R.  As most languages have different levels of expressivity for 'missing-ness', I think the best we can do is to indicate that, in the absences of an defined value, `commacomma` should be considered an undefined missing value in whatever language is being used to parse the file (unless collapse-delimiters=true).

**Comment by mobb** [comment]
so the recommendation should be (again, the prime directive) -- no hacks 
(updated the comment above to reflect that)

**Comment by mbjones** [comment]
I added an updated paragraph on the necessity of defining coded values and missing value codes.  See the changes in SHA ed2d5319e88ad813daa341cdea2ea6041fa1019f.
