### ISSUE TITLE
Set up doc website so XSDs resolve

### ISSUE THREAD

**Issue by amoeba** [NCEAS/eml#345]
@laurenwalker asked in NCEAS/#eml whether our intention was to make the new URIs for the schema resolve (e.g., https://eml.ecoinformatics.org/eml-2.2.0.xsd). Would this work or did we have some other plan?

I'm happy to make the change but wanted to give others a chance to comment.

**Comment by mbjones** [comment]
Yes, I intend for them to resolve.  I had not yet done so yet because I was contemplating the duplication between the `xsd` and `dist` directories if we copy them over directly.

**Comment by mbjones** [comment]
Just to be clear, the namespace for EML is:

https://eml.ecoinformatics.org/eml-2.2.0

I think that should resolve and return the 2.2.0 version of eml.xsd.  So, I plan to host that in a subdirectory at https://eml.ecoinformatics.org/eml-2.2.0/, and we will need a redirection rule to handle the redirect to eml.xsd.

**Comment by mbjones** [comment]
After talking with @amoeba, we agreed it would be good to refactor the build to work from source files rather than from a committed dist files to avoid duplication.  So now the deploy script creates the `dist` from scratch and deploys it to the `gh_pages` branch woihtout modifying the current branch. Please do not check in files to `dist`.

To get the XSD files to resolve, now just new to redirect the containing directory to the eml.xsd file.

- [ ] Make https://eml.ecoinformatics.org/eml-2.2.0 redirect to https://eml.ecoinformatics.org/eml-2.2.0/eml.xsd

**Comment by mbjones** [comment]
Netlify has a mechanism for redirects and rewrites: https://www.netlify.com/docs/redirects/

I deployed redirects for /eml-2.2.0 and it works and properly returns the schema documentation.
