### ISSUE TITLE
cardinality issue in documentation for children of literatureCited?

### ISSUE THREAD

**Issue by twhiteaker** [NCEAS/eml#376]
The [schema docs](https://eml.ecoinformatics.org/schema/eml-dataset_xsd.html#DatasetType_literatureCited) show this:

```xml
<literatureCited>
  <citation id="" scope="document" system="">{1,1}</citation>
  <bibtex>{1,1}</bibtex>
</literatureCited>
```

But the diagram shows one-to-many for children of literatureCited, so should the instance snippet be

```xml
<literatureCited>
  <citation id="" scope="document" system="">{1,unbounded}</citation>
  <bibtex>{1,unbounded}</bibtex>
</literatureCited>
```

Maybe the {1,1} has something to do with this being a xsd:choice?

**Comment by amoeba** [comment]
Hey @twhiteaker, thanks for the report. I agree it's a bit odd but it looks correct to me.

The cardinality is on the `CitationListType` and not the elements that make up the type. And the `{1,1}` cardinality looks like our documentation tool is just being complete since the `citation` and `bibtex` elements do have a `{1,1}` cardinality.

I'd like the examples you posted to look different but I haven't looked into whether or not we can customize the tool enough.

**Comment by twhiteaker** [comment]
ok thanks!
